### ISSUE TITLE
[FEATURE] Relic Commands

### ISSUE THREAD

**Issue by jaylac2000** [DuoIncure/ComplexRelics#2]
add relic names customize

add a relic command so i can add these to my crates 

example: /relic <type> <player> <amount>

**Comment by DuoIncure** [comment]
Relic names can be customised through the `config.yml`.

**Comment by jaylac2000** [comment]
ok, maybe add a configurable chance which these can be maintained. 

like 

chance: 1 

means 1/10

chance: 2

means 2/10 

etc 

1-10

**Comment by jaylac2000** [comment]
ah ok i see thats already there nvm

**Comment by DuoIncure** [comment]
In the latest update (v1.1.2) relic commands have been added!
There is option to give everyone a relic (/relicall) or there is the option to give a player a relic (/giverelic)
